[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "cf4970325195a80d6de4e31e3f99b0dd02e50da9"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "5a1952a45b8fe90a12ce8c5cc276bf41b21fd075f0e0edd74678f959fbbc6362"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "8b541f2be680476722b6c65559acfb6f67a9b968"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "ac9e82b865382bb3d45b7bd8ff691f7176e383d96374ec3a6f05837157c68067"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "fbe5332b9817ab5ce48ca5c637fd019d81b5ce7b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "01b25ec525a3553919ee8a56beeefcffbef431e0c9b5cf05c26050f60771ad43"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "8f8b9c3051f42c95732228b3116360ec756b05a9"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "7d0c8e0d237f65a18f5b142319eeadc7a80639bdf81e9191f524c1f0361de438"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "14d99c8e8a00f7c2b7e60131f8fea613733f0b15"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "69f5fe7e3c84e5694ff779d7fccdb53f077c0e469792e866963be83f301fb338"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "e2c5e16a84e53ae3f9c3ce4856e46c13b513fc9b"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "236605250a9489df2c073ed68f278cd3f66c787e85a1c932619f7a3fd7f96ab2"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "5b992f942fc1705e73b30dabd2a96a8c4ae8d648"
os = "windows"

    [[TetGen.download]]
    sha256 = "7fefbd11189f254e7348ccbec5b1e0fba8391d43e1475259db71d7718a380831"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "89e5bb6448bffba07cd2123b50529ea2fdc08aa8"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "8f603f547dcba6f6020dfbed26ee3d232f2cb37f976d7c5d81c65d0628961799"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "40fcae85624b7b57c8a588c7bf63c9811d5c7953"
os = "macos"

    [[TetGen.download]]
    sha256 = "8093907247767d8d09fb011c7e02e795889235ab956008263ef2dff4f0b43ed5"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-apple-darwin14.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "1af2022c0b6f935502c81061631f6cef549764d4"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "875073d578e0d9b9ed71f78728f6582e84841f923daeb44f782e8e8d18e51d55"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "328d3bcaf633705f79f03a14073d18ab3624e091"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "b40c5a445c1aaeb0e74f7ca6526d37ebee2e62123479170ec8c4245a6b705cbd"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "c839689f326fd4f76ce22c8ed2488339c43bf8d3"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "d85e392bff7af1e255b53675cc803c26722e441d990bb3307254a5c579b1ca6f"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-unknown-freebsd11.1.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "1f425cedc3eca66dfce8948c9c836d45e1ddd2f5"
os = "windows"

    [[TetGen.download]]
    sha256 = "f2e6445834e5c25789da90211f32e02573a2c41dd09999707ad4c11a224d04fd"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
