[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "3703f5529c896c08a4db95e7a9f43c627793ab1a"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "776c19f54bcc6727746f99cc0950782063ab53fcff130097e3dd3ac297941adc"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "6f6c7ac9fa67668510ec9b8f016ead31a906279e"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "2c611c1c3cf5ec96207435bc7cc92c3eee2ab2564b9421322cfd27edb2df33a1"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "07e14b53ea238a19b196222945edd55c3d037c6e"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "e1f2cf5e4e433084462959202a76c74e56aca430648faf8a71a4602849c43516"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "58495eac468462084ade812776c2e7afe99c2150"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "5ca2c344c6a8dd293a9d543fae299afb2dc5b23f4692dad3d2ca6766b684a10d"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "d06f2bed4a4026b0cd4e3a51f23ddb2efa3aca9b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "09d2d90146ab4e0c7af4e511a29a14e7be546e89d2ebce03a819acd08f7754fe"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "765b086be184acc75f4df60c6b8e8b5fe92889e6"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "af9fe3bd336f9c6c457b8f149bc044b1feb422b474ac13f46913aa351cdd8a6e"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "8855cd73aa95af681ee07d69d3c3becc16d6eed3"
os = "windows"

    [[TetGen.download]]
    sha256 = "4c5b8c0e03a6ff0a7f62f958fe786c064a28411272116bb8310532d9fcf46f45"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "491feb72c6712fb4d6d03aa8357342eee664b03c"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "5bc4840e46b1c1fef9a510c25e113ca89ac2d6d4e9adc73db8fb569bdfe9bbac"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "29881f5498e153dba43296f2f6b646ef86f5b889"
os = "macos"

    [[TetGen.download]]
    sha256 = "0b8b208b23cd33e08093a316b38d8f25e74252f7787d733e526f33b735ab82bc"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-apple-darwin14.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "13796f98ccf1e8f8f203b4b5ac82bae6ec55f7ba"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "8aa9f6bea8388ad0a105753c1f39c85ad05df2ad741024a954660f299febf3e7"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "c6b4b3b624b3c20621f5a822740cba6f5b19cdbc"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "804be5f4ed222f68a409a8d11928f0c2b30c5fd0c567a41320de358ace690b89"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "6d36be2ea2554ce0490723e7ca0531e51d57b16d"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "465ba1a00e534e3ae12fd6783a4f068ba60c985436850f958d9ef6ee8d7352dd"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-unknown-freebsd11.1.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "1794acbe1d3ce4bb283bb63c0b39a9873724e3dc"
os = "windows"

    [[TetGen.download]]
    sha256 = "7814123e53c5a48ee140f17ffa337dbb5f3288b5e4974afae8a3b3bd01c338fb"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
