[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "41ab34964996a2c6b039d9793ddb23501d042af5"
os = "macos"

    [[TetGen.download]]
    sha256 = "7be36a13de05b5ce0ead3ef270327930bb56dc773af0f2d980ac89dc66e3cc51"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.aarch64-apple-darwin.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "7089435f3e03c66532456b333ea47b21e60fd815"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "25411e14ece59eacad1e50861d0120d43c54ae5dc05c9fcdc98011b20eb704c3"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "d1ec23a8f81961e9cecd70790bd560c9c4dc8953"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "9efa73404d7af48f600a501503caed338d537547f94e91a2a051b66d8fac6ace"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c225950ea12aebda11f30a3a2897de75accee6b4"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "1318361434647d4ee4c0c246f174b94582e039ec2ce2db633dc57cf93e918666"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.armv6l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4d736ca037778c7c7d3810000d14b2ad701e1c32"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "047a6df62a09758c94fed8344531b31f20988dd3885b78c53971f37a7cdd1643"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.armv6l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e6915e39d9b41844a418df59186858dec24af9e"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "126a1661d23a13ab7b177fa94b614391abac9833999b8d8bd9741c6a0ba2ced6"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13fb8e4b1f04ff0a051f8bb1619487a46b6edb37"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "45b9fb1d23ab76749788f6b73e5890300595063ef551b360beba5156d96e9593"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "a7fefa75ebae725310d20ef4ae6d638a724c40ed"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "a4de0f13fcecfd7a3eae5bf64a119b428568e44c2ce9abe7585bcf5e0593fe1a"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "f2cab3d1a2451a65b76e9028d163fab68504848d"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "a0f8ba068aa07c8fc935351656144bad066cd1d8b38d7f541904cccce58d6285"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "08c1c929e508a343dbab508b3bd52edcee474ab5"
os = "windows"

    [[TetGen.download]]
    sha256 = "410f375857730198570b135ba1386a0a64df46445e81c9becae94b7a6c81f279"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "6849a144d786c9f3e9feae896ccc923c562d7ac5"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "13db269c3c454c51ebe7fe4a3fcdd1468d480ab22760bcf53c9a596663a6a1e9"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "325264408df94da43345231e78774fa05ef3ce8c"
os = "macos"

    [[TetGen.download]]
    sha256 = "cf9f923251091e969788d6a8fa5108d47e4215aa409a0020a40be8cf1a718a2e"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "2a2495e44bc4035dc8ba288efa243c3c16e64998"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "111678542895598e8af4ff29cbe69cbe0105267ffbd47bba4bd7605ec800331d"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "496fc32cd7a41826b65cdc8cb7674f6ec28587be"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "2be21f4281aba10209c5eaf5b48028a1b54496da76ef5464a2ec6fc9239cb5db"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "ecb9642e1a1e5994148e947f87e5b3e80186fc70"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "48d47059d92bddedc553d97e350b6216215647176b406ef9b9945f11635699ba"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "904bd5a239696557d3b5344452dbf9a09e61f721"
os = "windows"

    [[TetGen.download]]
    sha256 = "a8aed7684632435fbcf3248b9af1a433a31552ef2a20fd6d774e792c47c04fde"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.x86_64-w64-mingw32.tar.gz"
