[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "c0865fedafe915f23668b06f9b5949978899232c"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "c0417bcdb017ed3b1f184d54163e13f3875b2ed96544ecfb13525b6d8e091a82"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "b8b9714dd1d102d120f432529697d8fb9a699eb4"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "64c8bee7b209bd4aed00eae9e08ca1ee9a2c155c4f0f72b2675f38d9f448e2cd"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "0e2e103ff66726ad1be70ed776c5e7e107eaa3fa"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "dabdc88289b779b49ccc8fa88d3ab35e349f49eee568f0a58299944f73f3e66f"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "d854b64967b6b1104b516b06f907f1b144223305"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "9419e26600413baaa8279f363d5d092fa131825f9cb64286fdd0cf1fe70be565"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "b7105ce6d716bfa1fc99cc57475a8e09f1303705"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "ea3e42b5e4824b3a459295898b38b464dd2bb710088a5f30e95ecc692eaba800"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "2b06086b834591f357f3071ea40e61971a68ba26"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "c5522f48c9949a19b371cb3569f0a97fd61118080fee73e759249fd045550841"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "31235f5ef649ddb0cd15c88e743ac1fafaffa854"
os = "windows"

    [[TetGen.download]]
    sha256 = "3a7d1c11a683d60f1ded81462c1cbc4c978c4794c0a4cb98eca1836edd96cd3e"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "0fdfa144808e7fc58548937bf3e0460beffad015"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "a4c33fbd5d383c6c6b3c233e4696e5104d0aedbe025fca35651920d872d49323"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "df08e659e9401ba3c436ddcf1a9187e9300a896e"
os = "macos"

    [[TetGen.download]]
    sha256 = "126e81e7ac42443359c9368567b994e8aa314d32c9ced9bfc0a9db642e0ecd07"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-apple-darwin14.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "741e5042930997558990c1a84ad002ff6d5da81d"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "bb43741f901ca55f44259a2535ef072e662198afaa6ce016335ea8fe81c3b981"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "bd0c4f5a99ecb8f2baca3429925535cbdcd08b41"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "4f17299a3e775e92baa20ed94dc6da4d2a07870bdfd938f5c99067013def6ce8"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-unknown-freebsd11.1.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "065967d1dba0cf379b7ac5e1a8b935c6544b3672"
os = "windows"

    [[TetGen.download]]
    sha256 = "2c789a144d2c92a29c17f02e3258a1a02b4a0bf88b7db10c34455950297e5d8c"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "386409a2271c859d4be07c91af4929f776e426c7"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "7da05df37ee4e46d0097c71309cf15be69a8ba4db263d8d28dcbc03e71566351"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.2+1/TetGen.v1.5.2.x86_64-linux-gnu.tar.gz"
