[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "4c6f0036066b512dbb3773e359004b3ab4281d8b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "93e4ad9621a243438a65f838416dda2948550c49a10ee27758a95577bdec515d"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "53256f34904640ae58e78b43f8700ddcbee59f29"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "1188094fd042f73706bcbca8a5318bab87a8226ebfe935f2470497eb8547a6b6"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "c92c64178cbf5f3e1455feae9f3661d575978460"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "c8600789c097be8558d9b170c1abe53f25b25d8ce2ec3ef06d3f9ad423d228aa"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
git-tree-sha1 = "90a53824a38b1cc35eb95215ce9d13d3ae0cafc4"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "b281d8c018e29c56df1e49fc36a7417cc7a4fd01181e9bdbb36cbb44c7b59ae0"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "ed962009db19c92d769eb4654f997db6797fea5f"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "1e8dd342a11ebe2353c090f9dc0a535bfdf935a84cd3990a636ef67925b6e709"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "5994b85cc3cf5a9791b5b567cbb494678aa830dd"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "42a746a2f0debb5700f1c321e3c813c4e260b24fc685b7edc0e37f1d9bc5f7e0"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "1df27bdb403c3a515998958f96e75aa3089734b6"
os = "windows"

    [[TetGen.download]]
    sha256 = "727c996b31b4cb6a85633f009191da036336328f397fa1cd2c57ad65d1dc6796"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "140905390de13363632106108cd14765d9ceadef"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "5ecfb17131d130af2aa55ca5d61ee111c02b2fa7dbf49a77e9c49a07c1482ec4"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "4a8965c962e3f8b7b54eb20d9d1e4daa836d84ec"
os = "macos"

    [[TetGen.download]]
    sha256 = "14ce8621ae7d63f79f7aa4af290e6e4968b719b60c6bcd2ea8fa6b527308955c"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-apple-darwin14.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "1d35ff28097920d8dd983a6dff88e2c688b6a305"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "9399dd31dec1079af76440e141a17b442226287a8ebc8c1a1ff3ba4b52dac0ae"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "729f40c59b365c89fabf38cf6ea8ededaea2ba67"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "d0e8627373385cf16ca90b16c4f6ba56bd1847c30fb897808962e5dff638006e"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-unknown-freebsd11.1.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "c1e42677abe6fc2581d1f611b5559aaf38819f0a"
os = "windows"

    [[TetGen.download]]
    sha256 = "e93f90f6c83652c992f3c0a814d157e34278266c5baf6faa274de97580e4d7df"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "5ea38288786a7cfb4f2e291e7624c71127e5ccf8"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "6764fad55e180a84bcb4589cf47d3a86d6dc44bc5ca490ce50b549b67668bdf4"
    url = "https://github.com/j-fu/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-gnu.tar.gz"
